### ISSUE TITLE
Closing walls between thumb cluster and main body

### ISSUE THREAD

**Issue by kagoromo** [geoffder/dometyl-keyboard#6]
Hi,

Firstly, thank you for making this generator available. I think you have managed to incorporate many great features that make building a Dactyl-like keyboard a lot easier. (For me those would be the compatibility with BastardKB's shield PCB and simple tent/eyelets generations).

I'm currently using a handwired Skeletyl with the original design from BastardKB. It works perfectly, but I have come to realize that I wanted a "closed" version to hide the wiring mess inside. Starting with the dometyl's version of the Skeletyl as well as the Closed Splaytyl, I managed to reach halfway there: The columns are now connected and fully closed, eyelets are in correct spots, so the only thing left to do is connecting the thumb cluster with the main body.

![image](https://user-images.githubusercontent.com/9592129/190858376-92735e88-a8ce-4000-a1e5-fd23c8112106.png)

However, that last task turned out to be more difficult than I anticipated. My unfamiliarity with ocaml is the main roadblock to understand the Documentation fully, and I didn't really get anywhere just trying different Generator.Connect options, so I figured that I should look for help instead. 

Here is my very crude first stab at a Closed Skeletyl. Please advise me on how to achieve my goal (if it's even possible at the moment). Thank you very much!

https://github.com/kagoromo/dometyl-keyboard/blob/3358873e1051f339ca1889142dceba54c9ed996e/dometyl/lib/boards/skeletyl_but_closed.ml

**Comment by geoffder** [comment]
I'm afraid that proper full closure isn't something that it supports (somewhat of a non-goal for me, since the thumb is freed up to be more customizable without the extra stuff that might break). *However*, there is a bit more that you can do.

The [`~east_link`](https://github.com/kagoromo/dometyl-keyboard/blob/3358873e1051f339ca1889142dceba54c9ed996e/dometyl/lib/boards/skeletyl_but_closed.ml#L71) (and ~west_link) parameters let you control the connectors that run between the "first" thumb wall in the west and from the "last" back to the body in the west. The angles of the walls in the west make them a good candidate for a [`Connect.full_join`](https://github.com/geoffder/dometyl-keyboard/blob/9b33fecce617f6b6c7c55e9dfaa89c3a1183b5a3/dometyl/lib/generator/connect.mli#L60). a `full_join` might not work so nicely for the `~east_link`, but increasing the height of the connector there might give you more of the closed effect that you desire.

**Comment by kagoromo** [comment]
@geoffder Thank you for your answer. It seems like the result I wanted is not achievable with the options available. Still, thank you for your work!

**Comment by geoffder** [comment]
Ok, I'll go ahead and close this issue then.
