### ISSUE TITLE
Splaytyl 1u pcb's compatibility

### ISSUE THREAD

**Issue by toniz4** [geoffder/dometyl-keyboard#7]
Hello! 

I'm thinking about making a splaytyl keyboard with some slight changes, and I wish to use the 1u pcps that you showed in the Dartyl Choc Edition.

The 1u pcbs will be compatible with the splaytyl? 

Thanks for developing this awesome project!

**Comment by geoffder** [comment]
Yes you *should* be able to fit them in fine. Some areas may be a bit tight (I haven't done it myself), since the columns are jammed pretty close in to eachother, especially to accomodate the splayed columns. I don't think that it would be something that some post print processing can't get around though. 

By the way, I've finally just merged in the upgrades to the generator I had on the backburner for a while, so I hope you can pull the changes and give it a try.

**Comment by toniz4** [comment]
So I'm gonna try printing them. Either way I could resort to direct wire some keys too.

And something unrelated, I plan to use a xiao ble in my project, with a custom bastardkb adapter. So I will not be needing the trrs hole. I made some changes to the module that deals with that, making the trrs hole optional. Is that something you are interested in adding?

**Comment by geoffder** [comment]
Yea making the trrs hole optional would be fine with me.

**Comment by geoffder** [comment]
I've added a `?trrs` parameter to `BastardShield.make` to make the port hole optional: https://github.com/geoffder/dometyl-keyboard/commit/3cb13b18eb5e1284b75c40166a8301b5f6a8960c
